### ISSUE TITLE
Unexpected query string

### ISSUE THREAD

**Issue by danielgasparpereira** [Mazeakin/jquery-bootstrap-autofill#2]
The query string sent to server is something like this:

?_=1671236701487

![image](https://user-images.githubusercontent.com/50827392/208213982-2cf26f2d-252d-4608-b283-0f6e0c49dc27.png)

Any suggestions?

Thanks

**Comment by Gataquadrada** [comment]
Hi!

Could you paste the snippet that activates the plugin for your field?  
I need your current options object to simulate on my end.

**Comment by danielgasparpereira** [comment]
Here the Django rendered template:

```
<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="[/static/bootstrap-5.2.2-dist/css/bootstrap.min.css](http://localhost:8000/static/bootstrap-5.2.2-dist/css/bootstrap.min.css)" rel="stylesheet">

        <link rel="stylesheet" type="text/css" href="[/static/proyectos/style.css](http://localhost:8000/static/proyectos/style.css)">>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
        <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
        <script type="text/javascript" src="[/static/autocomplete/source/autofill.js](http://localhost:8000/static/autocomplete/source/autofill.js)"></script>

</head>
<body>
<form method="POST" enctype="multipart/form-data" action=" /proyectos/tareas/crear/">
  <input type="hidden" name="csrfmiddlewaretoken" value="2azxVfZrxWTqT6n1cYzoPSoK5Y1x4dnS63AIeNUKICi8ctDRE3sTwLVqaR8hYKLb">

 <div id="div_id_codigo_emplazamiento" class="mb-3"> <label for="id_codigo_emplazamiento" class="form-label requiredField">
                Codigo emplazamiento<span class="asteriskField">*</span> </label> <input type="text" name="codigo_emplazamiento" class="textinput textInput form-control" required id="id_codigo_emplazamiento"> </div> 
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
        <button type="submit" class="btn btn-primary">Crear</button>
      </form>

  <script>
    $("#id_codigo_emplazamiento").autofill({
      datasetURL: "/proyectos/emplazamientos/autocompletar",
      datasetMethod: "GET",
      datasetHeaders: {},
      minCharacters: 2,
    })
  </script>

<script src="[/static/bootstrap-5.2.2-dist/js/bootstrap.bundle.min.js](http://localhost:8000/static/bootstrap-5.2.2-dist/js/bootstrap.bundle.min.js)" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

</body>
```
I expect to receive something like `?q=text`

**Comment by Gataquadrada** [comment]
Hopefully, fixed in the most recent [update](https://github.com/Mazeakin/jquery-bootstrap-autofill/commit/e60cb1638bb7879fa6539c524ace2c8166be8fd2).
Thank you for letting me know.

**Comment by danielgasparpereira** [comment]
I'm not sure if is me as a newbie, or is a Django related issue, but still receiving query string in same way. In Chrome I see the same. Here a screenshot, hope it helps.

![image](https://user-images.githubusercontent.com/50827392/208549971-d725ed85-a3e8-440a-8dbe-d0b096be5f6b.png)

In server side, I've made an automatic results response just for testing pourpose. 

```
def EmplazamientoAutocompletar(request):
    print(request.GET)
    results = {'VX1033':1, 'VX0000':2}
    return JsonResponse(results)
```
What I expect to receive is a query string with the text typed to fetch it on the server.

Thank you.

**Comment by Gataquadrada** [comment]
Make sure to have downloaded (and uncached) the newest version.

You indeed made me aware of the aforementioned bug. But, as far as I could reproduce your settings, I got the expected result:
<img width="232" alt="image" src="https://user-images.githubusercontent.com/6697480/208558562-bebdaead-d649-4705-a8e9-d25cb28dda82.png">

I can't help you with Django. As I've never heard of it. 
The best I can do (and did) is add a [debug mode](https://github.com/Mazeakin/jquery-bootstrap-autofill/commit/427816323b4bd69951c07b346fa51c0ff2e0c53e). Maybe give it a try?

**Comment by danielgasparpereira** [comment]
As I suspected, it was because I'm a newbie. It was not necessary to try debug mode. It was cached as you said. So now, it works perfectly.
By the way debug mode works fine too!
Thank you very much for your help

**Comment by Gataquadrada** [comment]
No worries, mate. Making mistakes is part of the process.
Glad you managed to find the solution.
